definitions:
  controller.PairRes:
    properties:
      asset_decimals:
        items:
          type: integer
        type: array
      asset_infos:
        items:
          $ref: '#/definitions/dezswap.AssetInfoRes'
        type: array
      contract_addr:
        type: string
      liquidity_token:
        type: string
    type: object
  controller.PoolRes:
    properties:
      address:
        type: string
      assets:
        items:
          $ref: '#/definitions/dezswap.AssetInfoRes'
        type: array
      total_share:
        type: string
    type: object
  controller.TokenRes:
    properties:
      chainId:
        type: string
      decimals:
        type: integer
      icon:
        type: string
      name:
        type: string
      protocol:
        type: string
      symbol:
        type: string
      token:
        type: string
      total_supply:
        type: string
      verified:
        type: boolean
    type: object
  dezswap.AssetInfoRes:
    properties:
      amount:
        type: string
      info:
        $ref: '#/definitions/dezswap.AssetInfoTokenRes'
    type: object
  dezswap.AssetInfoTokenRes:
    properties:
      native_token:
        $ref: '#/definitions/dezswap.NativeTokenAssetInfoRes'
      token:
        $ref: '#/definitions/dezswap.TokenAssetInfoRes'
    type: object
  dezswap.NativeTokenAssetInfoRes:
    properties:
      denom:
        type: string
    type: object
  dezswap.TokenAssetInfoRes:
    properties:
      contract_addr:
        type: string
    type: object
  httputil.BadRequestError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: bad request
        type: string
    type: object
  httputil.InternalServerError:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: internal server error
        type: string
    type: object
  httputil.NotFoundError:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: not found
        type: string
    type: object
info:
  contact: {}
paths:
  /pairs:
    get:
      consumes:
      - application/json
      description: get Pairs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.PairRes'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.BadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.InternalServerError'
      summary: All Pairs
      tags:
      - pairs
  /pairs/{address}:
    get:
      consumes:
      - application/json
      description: get Pair by Address
      parameters:
      - description: Pair Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.PairRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.BadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.InternalServerError'
      summary: Get a pair
      tags:
      - pairs
  /pools:
    get:
      consumes:
      - application/json
      description: get Pools
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.PoolRes'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.InternalServerError'
      summary: All Pools
      tags:
      - pools
  /pools/{address}:
    get:
      consumes:
      - application/json
      description: get Pool by Address
      parameters:
      - description: Pool Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.PoolRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.InternalServerError'
      summary: Get a pool
      tags:
      - pools
  /tokens:
    get:
      consumes:
      - application/json
      description: get Tokens
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.TokenRes'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.InternalServerError'
      summary: All Tokens
      tags:
      - tokens
  /tokens/{address}:
    get:
      consumes:
      - application/json
      description: get Token by Address
      parameters:
      - description: Token Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.TokenRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.InternalServerError'
      summary: Get a token
      tags:
      - tokens
swagger: "2.0"
