[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} \
  ([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/dezswap/dezswap-api/commit/{{ commit.id }}))\
  {% if commit.remote.pr_number %}[#{{ commit.remote.pr_number }}](https://github.com/dezswap/dezswap-api/pull/{{ commit.remote.pr_number }}){% endif %}\
{% endfor %}
{% endfor %}\n
"""
footer = """
{% for release in releases %}\
{% if release.version %}\
{% if release.previous.version %}\
[{{ release.version | trim_start_matches(pat="v") }}]: \
  https://github.com/dezswap/dezswap-api/compare/{{ release.previous.version }}...{{ release.version }}
{% else %}\
[{{ release.version | trim_start_matches(pat="v") }}]: \
  https://github.com/dezswap/dezswap-api/releases/tag/{{ release.version }}
{% endif %}\
{% else %}\
[Unreleased]: https://github.com/dezswap/dezswap-api/compare/{{ release.previous.version }}...HEAD
{% endif %}\
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false

commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^refactor", group = "Changed" },
  { message = "^perf", group = "Changed" },
  { message = "^revert", group = "Fixed" },
  { message = "^docs", skip = true },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
  { message = "^test", skip = true },
  { message = "^build", skip = true },
]

filter_commits = true
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

[remote.github]
owner = "dezswap"
repo = "dezswap-api"
