indexer:
  src_db:
    host: localhost
    port: 5432
    database: dezswap_api
    username: app
    password: appPW
  indexer_db:
    host: localhost
    port: 5432
    database: indexer
    username: app
    password: appPW
