indexer:
  chain_id: cube_47-5
  src_node:
    host: 10.0.0.1
    port: 9090
    factory:
  src_db:
    host: localhost
    port: 5432
    database: dezswap_api
    username: app
    password: appPW
  db:
    host: localhost
    port: 5432
    database: indexer
    username: app
    password: appPW
