indexer:
  chain_id: cube_47-5
  src_node:
    host: 10.0.0.1
    port: 9090
    factory:
  src_db:
    host: localhost
    port: 5432
    database: dezswap_api
    username: app
    password: appPW
  db:
    host: localhost
    port: 5432
    database: dezswap_api
    username: app
    password: appPW

log:
  level: debug
  format_json: true
  env:

sentry:
  dsn:

api:
  server:
    name: dezswap-api
    host: 0.0.0.0
    port: 8000
    swagger: false
    mod: release # test, debug, release
    version:
    chain_id:
  db:
    host: localhost
    port: 5432
    database: dezswap_api
    username: app
    password: appPW
  # request cache for api
  cache:
    memory_cache: true # true, false it indicates whether to use in-memory cache
    redis: # optional
      host: localhost
      port: 6379
      user: default
      password: appPW
      db: 0 # optional redis db index default is 0
      protocol: 3 # optional redis protocol index default is 3
      tls_enabled: true # optional redis tls enabled default is false
